### ISSUE TITLE
Not fetch-ing data from json file

### ISSUE THREAD

**Issue by marianadates** [varunon9/amp4email#2]
I was playing around with the playground (https://amp.gmail.dev/playground/) and it was not working to read data from json. I am getting a refuse to connect and a fail to fetch error.
After trying more options I saw that also on the examples available in the playground `<amp-list>` and `<amp-list> #2` there are the same errors, so it is not because of my json. 
PS: In the old playground(https://playground.amp.dev) everything is working, but I am not able to test the email properly.
<img width="2235" alt="Screenshot 2019-06-28 at 12 49 29" src="https://user-images.githubusercontent.com/49152400/60337383-376b2b00-99a3-11e9-818e-af4f980bd35c.png">

**Comment by varunon9** [comment]
https://amp.gmail.dev/playground/ This is **amp4email** playground
https://playground.amp.dev This is just AMP playground

In **amp4email** if you want to test API call, you'll have to test it from your own HTTPS enabled server because amp4email API request (actually a Gmail proxy) expects following headers-

```
Access-Control-Allow-Origin: https://mail.google.com
AMP-Access-Control-Allow-Source-Origin: <your sender email address>
Access-Control-Expose-Headers: AMP-Access-Control-Allow-Source-Origin
```

See this: https://developers.google.com/gmail/ampemail/security-requirements

https://stackoverflow.com/questions/52526339/amp-form-always-showing-submit-error-even-on-response-code-200/56339308#56339308

**Comment by marianadates** [comment]
Thank you for your response, I have managed to fix the problem I had. Now it is properly getting my data.
